### ISSUE TITLE
Ensure hey-apm can push enough load to apm-server to make it drop events

### ISSUE THREAD

**Issue by jalvz** [elastic/hey-apm#105]
(aka, trigger a full queue without breaking the ES link)

**Comment by jalvz** [comment]
So far, i failed setting `ELASTIC_APM_API_BUFFER_SIZE` to max value

If I start several processes, some appear to succeed completely, and others to fail completely

**Comment by jalvz** [comment]
The only way around that I can see is with distributed load testing:
Very high level, the orchestrator process would spin some machines to perform a benchmark, all with same parameters and `benchmark_id`. Then that same process can make the right aggregation query to check for regressions.
Dashboards should work the same as they use averages for everything.

@graphaelli what do you think?

**Comment by graphaelli** [comment]
Distributing the load testing makes sense - can we generate enough load from a single host with multiple processes for now or are you envisioning coordination among multiple hosts?

**Comment by jalvz** [comment]
When I wrote that I was thinking multiple hosts, but yeah, starting with one seems more sensible.

**Comment by jalvz** [comment]
This seem to be solved on the newest CI setup. Will keep an eye on things, will close for now
