### ISSUE TITLE
[apm-ci] Run hey-apm unit tests on CI

### ISSUE THREAD

**Issue by jalvz** [elastic/hey-apm#137]
We have automated apm-server benchmarks with hey-apm on CI, but we do not have yet automation on hey-apm itself.

We need a new pipeline that runs on every hey-apm PR and executes `go test -v`.

This is low priority (there is just 1 unit test at the moment :sunglasses: but we will add more).

**Comment by mdelapenya** [comment]
Hey @jalvz, here we are already executing the unit tests:

- Jenkinsfile: https://github.com/elastic/hey-apm/blob/master/.ci/Jenkinsfile#L56
- Shell script: https://github.com/elastic/hey-apm/blob/master/scripts/jenkins/unit-test.sh#L33
- Job execution for a PR: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-hey-test-mbp/detail/PR-138/1/pipeline/66

is that what you mean?

**Comment by jalvz** [comment]
lol, yes. totally missed that it was in place already :see_no_evil: 
thanks!
