### ISSUE TITLE
add possibility to trigger hey-apm benchmark from apm-server PR

### ISSUE THREAD

**Issue by jalvz** [elastic/hey-apm#146]
This came up yesterday in a @elastic/apm-server call as a feature request.

It needs some non trivial changes, as currently this uses the latest snapshot server image

**Comment by kuisathaverat** [comment]
Would it be triggered always or only when you request it? I mean it seems a little overhead to launch a benchmark test on every PR on every commit.

**Comment by jalvz** [comment]
yes, sorry, upon request only

**Comment by kuisathaverat** [comment]
>It needs some non trivial changes, as currently this uses the latest snapshot server image

The pipeline can build a local Docker image with a fixed version tag that we would use to launch the Hey APM test, I think this would make that you do not need to change anything in code
