### ISSUE TITLE
ci: use a baremetal machine for benchmarks

### ISSUE THREAD

**Issue by axw** [elastic/hey-apm#157]
hey-apm benchmark jobs are currently running on immutable/ephemeral cloud instances. We should consider using a baremetal machine for running apm-server, for more predictable benchmarks.

**Comment by v1v** [comment]
@axw , the benchmark stage runs in a baremetal, although it does spin up the apm-server (and other services) in a docker container:
- See [benchmark](https://github.com/elastic/hey-apm/blob/master/.ci/scheduled-benchmark.groovy#L78-L92) stage
- See [docker-script](https://github.com/elastic/hey-apm/blob/master/.ci/scripts/run-bench-in-docker.sh).

See https://github.com/elastic/hey-apm/pull/125 as the initial approach. I guess this is the follow up :)

I've got some questions, what's the requirement for this ticket? To run the apm-server in an isolated baremetal and the benchmarks in another instance (cloud based or also a baremetal one?  Or a totally different approach?

**Comment by axw** [comment]
Sorry @v1v, I expected to find that in the Jenkinsfile. This issue is invalid.

It would probably be ideal to run apm-server isolated, directly on the machine, but I don't have a feel for how much hey-apm interferes with apm-server's performance. I suspect it's marginal. I'll close this until we identify some interference.
