### ISSUE TITLE
CPU usage high between tests

### ISSUE THREAD

**Issue by roncohen** [elastic/hey-apm#28]
In my experiments, it seems like hey-apm is still working on something even after the test ends when using "interactive" mode. In itself that's not necessarily bad, however if the hey-apm workload accumulates as you do more tests, it could end up affecting the tests themselves.

**Comment by jalvz** [comment]
Thanks for the report, there are many externalities and moving parts, i'm sure this is leaving some unclosed channels around or something

**Comment by jalvz** [comment]
this is from an older version, closing as outdate
