### ISSUE TITLE
Create CI job only for unit tests

### ISSUE THREAD

**Issue by jalvz** [elastic/hey-apm#45]
Right now unit tests run as part of stress tests.

There should be a job for them that triggers on PR's

**Comment by kuisathaverat** [comment]
On [PR](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-hey-test-mbp/detail/PR-69/35/pipeline/41) pipeline unit and stress tests are in different stages, so they can run in different cases based on 'when' conditions (PRs, branches, tags, ...), Is that what you want? or you want a job to run only the stress tests on a PR of apm-server for example.

**Comment by jalvz** [comment]
yeah, that is great! for stress tests is enough to run them once a day

**Comment by kuisathaverat** [comment]
I create a new pipeline that runs only the stress test, it is scheduled to run once a day  https://github.com/elastic/hey-apm/pull/69/commits/f02a18d86777a658b01d3ee6bc2fb385df800e2a

**Comment by jalvz** [comment]
thanks @kuisathaverat. for now, that should run checkout the `v1` branch of this repo.
we don't have yet load tests for `v2` (master)

**Comment by kuisathaverat** [comment]
@jalvz what about the APM server version? 6.5 or master

**Comment by jalvz** [comment]
master!

good question, tho, it might makes sense going forward to add release branches to the mix, but for the V1 api is not worth the trouble.

thanks :+1:

**Comment by kuisathaverat** [comment]
Done, the scheduled task will use APM server master branch and Hey APM v1 branch, if you launch it manually you can change those values.
