### ISSUE TITLE
[Hey APM][v2] Add v2 hey-apm tests to CI

### ISSUE THREAD

**Issue by jalvz** [elastic/hey-apm#56]

**Comment by kuisathaverat** [comment]
The integration test runs some v2 test in master and 6.x branches.

**Comment by simitt** [comment]
I'd not be aware that the integration tests do use hey-apm in any way. Afaics the testsuite for hey-apm is only run against [master](https://apm-ci.elastic.co/job/apm-server/job/apm-hey-test-mbp/job/master/).

**Comment by kuisathaverat** [comment]
@simitt 
I was thinking about the integration test, but this is related to Hey APM, so we need to run it on v1 and v2-stream-support branches and schedule a daily build, isn't it?

**Comment by simitt** [comment]
Yes, that's the goal. I might have misunderstood your comment then.

**Comment by jalvz** [comment]
This requires almost all of https://github.com/elastic/hey-apm/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+created%3A%3C2019-03-27

**Comment by jalvz** [comment]
done in https://github.com/elastic/hey-apm/pull/116, will add another issue for the automation bit
