### ISSUE TITLE
Read back the response from apm-server

### ISSUE THREAD

**Issue by jalvz** [elastic/hey-apm#58]
With the streaming API, all calculations should be event based instead of request based.
We need this to know how many events have been rejected

**Comment by simitt** [comment]
@juan haven't you adapted this with the report changes you did?

**Comment by jalvz** [comment]
sort of. we still don't read back the response from apm-server thou, but if you think is good enough we can close this

**Comment by simitt** [comment]
Ah right, we don't do that yet. I think it is fair to keep it open then.
