### ISSUE TITLE
Fix tests on CI

### ISSUE THREAD

**Issue by simitt** [elastic/hey-apm#66]
Currently the stress tests fail on CI.

**Comment by jalvz** [comment]
@kuisathaverat I think we should remove current hey-apm tests from CI, which are based on v1, and focus on adding tests for 7.x (v2). I'll add the tasks for that.

In the meanwhile ll remove the tests from the codebase soon, can you disable/remove the existing pipeline, and then close this issue? It will just keep failing

**Comment by kuisathaverat** [comment]
@jalvz 
Is it completely broken? Are not any combination that works at all? if so, I'd disable all stages

**Comment by jalvz** [comment]
Yes, i think disabling all is what makes most sense.
The goal of this is to catch performance regressions over time as we grow the apm-server, and we won't touch v1 never again.

**Comment by kuisathaverat** [comment]
done https://github.com/elastic/hey-apm/pull/95
