### ISSUE TITLE
Add tests for the RUM agent

### ISSUE THREAD

**Issue by simitt** [elastic/hey-apm#71]
This is required for testing the RUM endpoint.

**Comment by jalvz** [comment]
I updated the title to reflect the ultimate goal. Lets track the pre-requisites separately when we come to this

**Comment by jalvz** [comment]
This is probably so complicated and the benefit so small (in the light of other limitations we have), that I don't think is worth it... But maybe it is worth reopening if we have concrete ideas of how we can actually do it.
