### ISSUE TITLE
Get data from the running process

### ISSUE THREAD

**Issue by jalvz** [elastic/hey-apm#93]
- [x] Get version info from the root endpoint (instead of using Git commands)
- [x] Get performance/monitoring data from the expvar endpoint

**Comment by graphaelli** [comment]
expvar can't be enabled or reached on production - we could fall back to xpack monitoring for mem/cpu and live without the rest of the metrics in ess for now.

**Comment by jalvz** [comment]
ref https://github.com/elastic/hey-apm/pull/101

**Comment by jalvz** [comment]
done in #101 and #104
